x,y,z=map(int,input().split())
if(x==y==z):
    print(10000+x*1000)
elif(x==y or y==z or x==z):
    if(x==y):
        print(1000+x*100)
    else:
        print(1000+z*100)
else:
    if(x>y):
        if(x>z):
            print(x*100)
        else:
            print(z*100)
    else:
        if(y>z):
            print(y*100)
        else:
            print(z*100)